// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh5N5nzkOw7WKnG3trLY05OJ9XyjDdJ_Q',
    appId: '1:304195718935:web:423c7a78c5aa4c8f65b152',
    messagingSenderId: '304195718935',
    projectId: 'flipflow-7c658',
    authDomain: 'flipflow-7c658.firebaseapp.com',
    storageBucket: 'flipflow-7c658.firebasestorage.app',
    measurementId: 'G-FSW3PJQWFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWhZaBS17wXMR37-zOiQlzcuDswYF5tNE',
    appId: '1:304195718935:android:ab1139efbd70006c65b152',
    messagingSenderId: '304195718935',
    projectId: 'flipflow-7c658',
    storageBucket: 'flipflow-7c658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFYpeYZBjsjuHUk0iKEwruO9_rMigzvGY',
    appId: '1:304195718935:ios:54466c4b0db243c365b152',
    messagingSenderId: '304195718935',
    projectId: 'flipflow-7c658',
    storageBucket: 'flipflow-7c658.firebasestorage.app',
    iosBundleId: 'com.example.flipflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFYpeYZBjsjuHUk0iKEwruO9_rMigzvGY',
    appId: '1:304195718935:ios:54466c4b0db243c365b152',
    messagingSenderId: '304195718935',
    projectId: 'flipflow-7c658',
    storageBucket: 'flipflow-7c658.firebasestorage.app',
    iosBundleId: 'com.example.flipflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh5N5nzkOw7WKnG3trLY05OJ9XyjDdJ_Q',
    appId: '1:304195718935:web:2eba1f83a6906f0365b152',
    messagingSenderId: '304195718935',
    projectId: 'flipflow-7c658',
    authDomain: 'flipflow-7c658.firebaseapp.com',
    storageBucket: 'flipflow-7c658.firebasestorage.app',
    measurementId: 'G-RHMJ3QSFYG',
  );

}